name: themakerspace
description: MontyMakerspace

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  json_theme: ^4.0.0
  http: ^0.13.0
  url_launcher: ^6.1.10
  flutter_secure_storage: ^8.0.0
  window_size:
      git:
        url: https://github.com/google/flutter-desktop-embedding.git
        path: plugins/window_size
        ref: main
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_login: ^4.2.0
  flutter_material_pickers: ^3.6.0
  list_treeview: ^0.3.1

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/themes/
    - assets/icons/
